MODEL:
  NAME: 'ProtoNet'
  DEVICE_ID: ('0')


TASK:
    N_WAY: 5
    N_SHOT: 5
    N_QUERY: 15

RANDOM:
  SEED: 123

DATASET:
  NAME: 'Fusion'
#  TRAIN_PATH: '/home/scusw1/malware/datas/LargePE/data/train/img.pt'
#  VAL_PATH: '/home/scusw1/malware/datas/LargePE/data/val/img.pt'
#  TEST_PATH: '/home/scusw1/malware/datas/LargePE/data/test/img.pt'
#  BASE_PATH: '/home/scusw1/malware/datas/LargePE/data/'

  TRAIN_PATH: '/home/scusw1/malware/datas/virushare-20/data/train/img.pt'
  VAL_PATH: '/home/scusw1/malware/datas/virushare-20/data/val/img.pt'
  TEST_PATH: '/home/scusw1/malware/datas/virushare-20/data/test/img.pt'
  BASE_PATH: '/home/scusw1/malware/datas/virushare-20/data/'


DATALOADER:
  BATCH_SIZE: 1
  NUM_WORKERS: 0

TRAIN:
  EPOCH: 50000
  VAL_PER_EPOCH: 100
  VAL_TASK: 1000
  TEST_TASK: 5000

SOLVER:
#  OPTIMIZER: 'SGD'
  OPTIMIZER: 'Adam'
  MAX_EPOCHS: 5000

  BASE_LR: 0.001
  LOSS_FN: 'CrossEntropyLoss'


LOGGING:
  BASE_DIR: '/home/scusw1/malware/fusion/log/'
  TASK_NAME: '5-way-5-shot'
  MAX_MODEL: 5
  DESCRIBE: ""